function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
	--Cullinan
	AddTextEntry("NPCUL", "Cullinan")
	AddTextEntry("RROYCE", "Rolls Royce")
	AddTextEntry("NPCUL_EMB1", "Black Ornament")
	AddTextEntry("NPCUL_TBLACK_BUMF", "Front Bumper Dechrome")
	AddTextEntry("NPCUL_TBLACK_BUMR", "Rear Bumper Dechrome")
	AddTextEntry("NPCUL_TRIM_BLACK", "Bodyshell Dechrome")
	AddTextEntry("NPCUL_LIGHT_BLACK", "Light Dechrome")
	AddTextEntry("NPCUL_EURO", "Euro Style Plate")
	AddTextEntry("NPCUL_MIRR", "Black Mirrors")
	AddTextEntry("NPCUL_INT_00", "Black Interior Trim")
	AddTextEntry("NPCUL_INT_01", "Wood Interior Trim")
	AddTextEntry("NPCUL_INT_02", "Carbon Interior Trim")
	--Bentley Flying Spur
	AddTextEntry("BNTLY", "Bentley")
	AddTextEntry("NPBFS", "Flying Spur (2020)")
	AddTextEntry("NPBFS_TBLACK_BON", "Bonnet Dechrome")
	AddTextEntry("NPBFS_TBLACK_EXH", "Exhaust Dechrome")
	AddTextEntry("NPBFS_ROOF", "Painted Roof")
	AddTextEntry("NPBFS_EXH2", "Titanium Exhaust")
	--GT4 RS
	AddTextEntry("PORSCHE", "Porsche")
	AddTextEntry("NPGT4", "718 GT4 RS")
	AddTextEntry("NPGT4_BOOT_1", "Carbon Frunk")
	AddTextEntry("NPGT4_BUMF1", "Carbon Splitter")
	AddTextEntry("NPGT4_BUMR_1", "Carbon Diffuser")
	AddTextEntry("NPGT4_ROOF_A", "Carbon Roof")
	AddTextEntry("NPGT4_BON1", "Carbon Bonnet")
	AddTextEntry("NPGT4_SPOILER", "Aero Package")
	AddTextEntry("NPGT4_SPOILER2", "No Spoiler")
	AddTextEntry("NPGT4_MIRROR", "Carbon Mirrors")
	AddTextEntry("NPGT4_LILSPL", "Carbon Small Spoiler")
	AddTextEntry("NPGT4_VENTS", "Vent Cover Delete")
	AddTextEntry("NPGT4_EXH_RACE", "Race Exhaust")
	--Tesla Model S
	AddTextEntry("TESLA", "Tesla")
	AddTextEntry("NPMDLS", "Model S")
	AddTextEntry("NPMDLS_SKIRT", "Prior Design Kit")
	AddTextEntry("NPMDLS_SKIRT2", "Widebody Prior Design Kit")
	AddTextEntry("NPMDLS_AERO", "Aero Package")
	AddTextEntry("NPMDLS_SPL1", "Remove Spoiler")
	AddTextEntry("NPMDLS_SPL2", "Prior Design Spoiler")
	--Nissan Proto Z
	AddTextEntry("NISSAN", "Nissan")
	AddTextEntry("NPZPROTO", "Proto Z")
	AddTextEntry("NPZPROTO_AERO", "Aero Package")
	AddTextEntry("NPZPROTO_SPL1", "Remove Spoiler")
	AddTextEntry("NPZPROTO_SPL1A", "Carbon Stock Spoiler")
	AddTextEntry("NPZPROTO_SPL0", "Primary Lip Spoiler")
	AddTextEntry("NPZPROTO_SPL0A", "Carbon Lip Spoiler")
	AddTextEntry("NPZPROTO_SPL2", "Primary Race Spoiler")
	AddTextEntry("NPZPROTO_SPL2A", "Carbon Race Spoiler")
	AddTextEntry("NPZPROTO_SPL3", "Primary GT Spoiler")
	AddTextEntry("NPZPROTO_SPL3A", "Carbon GT Spoiler")
	AddTextEntry("NPZPROTO_SPL4", "Primary Low Spoiler")
	AddTextEntry("NPZPROTO_SPL4A", "Carbon Low Spoiler")
	AddTextEntry("NPZPROTO_SPL5", "Primary Drift Spoiler")
	AddTextEntry("NPZPROTO_SPL5A", "Carbon Drift Spoiler")
	AddTextEntry("NPZPROTO_SPL6", "Primary Time Attack Spoiler")
	AddTextEntry("NPZPROTO_SPL6A", "Carbon Time Attack Spoiler")
	AddTextEntry("NPZPROTO_EXH1", "Race Exhaust")
	AddTextEntry("NPZPROTO_EXH1A", "Titanium Race Exhaust")
	AddTextEntry("NPZPROTO_EXH2", "Angled Exhaust")
	AddTextEntry("NPZPROTO_EXH2A", "Titanium Angled Exhaust")
	AddTextEntry("NPZPROTO_EXH3", "Shotgun Exhaust")
	AddTextEntry("NPZPROTO_EXH3A", "Titanium Shotgun Exhaust")
	AddTextEntry("NPZPROTO_TRIM1", "Primary Trim")
	AddTextEntry("NPZPROTO_TRIM2", "Secondary Trim")
	AddTextEntry("NPZPROTO_TRIM3", "Carbon Trim")
	AddTextEntry("NPZPROTO_TRIM4", "Black Trim")
	AddTextEntry("NPZPROTO_BUMF1", "Carbon Front Splitter")
	AddTextEntry("NPZPROTO_BUMR1", "Carbon Rear Diffuser")
	AddTextEntry("NPZPROTO_SKIRT1", "Carbon Skirts")
	AddTextEntry("NPZPROTO_BON1", "Carbon Bonnet")
	AddTextEntry("NPZPROTO_BON2", "Smooth Bonnet")
	AddTextEntry("NPZPROTO_BON2A", "Carbon Smooth Bonnet")
	AddTextEntry("NPZPROTO_BON3", "Vented Bonnet")
	AddTextEntry("NPZPROTO_BON3A", "Carbon Vented Bonnet")
	AddTextEntry("NPZPROTO_BON4", "Drift Bonnet")
	AddTextEntry("NPZPROTO_BON4A", "Carbon Drift Bonnet")
	AddTextEntry("NPZPRT_EYELID1", "Primary Eye Lid")
	AddTextEntry("NPZPRT_EYELID2", "Carbon Eye Lid")
	AddTextEntry("NPZPRTO_RB26SWP", "Nissan RB26 Engine Swap")
	AddTextEntry("NPZPROTO_2JZSWAP", "Toyota 2JZ Engine Swap")
	AddTextEntry("NPZPRT_F20CSWAP", "Honda F20C Engine Swap")
	AddTextEntry("NPZPROTO_V8SWAP", "Generic V8 Engine Swap")
	AddTextEntry("NPZPROTO_BRACE_1", "Street Strut Brace")
	AddTextEntry("NPZPROTO_BRACE_2", "Triangle Strut Brace")
	AddTextEntry("NPZPROTO_BRACE_3", "Race Strut Brace")
	AddTextEntry("NPZPROTO_BRACE_4", "Rally Strut Brace")
end)